config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :lists, only: [:index, :new, :show, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, presence: true, length: { minimum: 6 }
  belongs_to :movie
  belongs_to :list
  validates :movie, presence: true
  validates :list, presence: true
  validates :movie_id, uniqueness: {scope: :list_id, message: "Must be unique per list"}
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to lists_path(@lists)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to restaurant_path(@bookmark.list), status: :see_other
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @movies = Bookmark.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path(@lists)
  end

  def add_movie
    @list = List.find(params[:id])
    @movies = Movie.all
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Create New Bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <nav class="navbar bg-black">
        <%= image_tag "movie_logo.png", alt: "Le Wagon", width: 50 %>
        <form class="d-flex ">
          <input type="submit" class="" value="My list">
          <input type="submit" class="" value="New List">
        </form>
      </nav>
    </div>
    <%= yield %>
  <footer class="footer bg-black">
    <div class="text-center">
      <p class="text-white">&copy; 2024 Your Company
      <i class="fab fa-facebook"></i>
      <i class="fab fa-twitter"></i>
      <i class="fab fa-instagram"></i></p>
    </div>
  </footer>
  </body>
</html>

app/views/lists/index.html.erb
<div class="card card-category">
  <img src="<%= image_tag 'mountain.jpg', alt: 'Breakfast' %>" class="card-img-top" alt="Breakfast">
  <div class="card-body">
    <h5 class="card-title">Breakfast</h5>
  </div>
</div>


<div class="container">
  <div class="row row-cols-1 row-cols-md-5 g-4">
    <% @lists.each do |list| %>
      <div class="col">
        <div class="card h-25 ">
          <%= image_tag "escape_room.jpeg", alt: "Le Wagon"%>  <div class="card-body">
          <h1 class="card-title text-center ">
            <%= link_to list.name, list_path(list), class: "list-link" %>
          </h1>
        </div>
      </div>
    </div>
  <% end %>
<div class="card">
  <button type="button" class="btn btn-success my-animated-button">
    <h1 class="text-center card-title mb-6">
      <i class="fa-solid fa-plus" style="color: white;"></i>
      <%= link_to "New list", new_list_path, class: "text-decoration-none", style: "color: white;"%>
    </h1>
  </button>
</div>

</div>

app/views/lists/new.html.erb
<div class"custom-background-img">
</div>
  <%= simple_form_for(@list) do |f| %>
    <div class="container text-center w-50">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
        <%= f.input :photo, as: :file %>
      </div>

      <div class="form-group">
        <%= f.submit "Create List", class: "btn btn-primary" %>

      </div>
    </div>
  <% end %>

app/views/lists/show.html.erb
### the page works###